### PR TITLE
Leguy/update toward cism3

### PR DESCRIPTION
**Pull request by gunterl**
This branch contains modification to CISM to be python3 compatible. Due to this change, the ross and ismip-hom test cases will no longer bit-for-bit with python2 version of the code while the other ones, to the best of my knowledge, should be.

### CODE REVIEW

**Comment by whlipscomb** [comment]
@gunterl, Thanks for carefully making and testing all these changes.  A few questions:
* Do you know why the ismip-hom test cases are no longer BFB with the python2 version?
* I noticed that the various MISMIP tests cases use optparse rather than argparse.  I read that optparse is now deprecated, so thinking we should update all the test scripts to use argparse, which is more flexible for adding command-line options.
* Along these lines, are there any other examples of deprecated modules that we should be moving away from?

**Comment by gunterl** [comment]
> @whlipscomb 
With the latest commit I replaced the calls to optparse by argparse and made sure that the default ISMIP-hom test were very similar than the older results (while not BfB). The plotting script for ISMIP-hom is now working for the default experiments.
I tried to look through the different modules that are now deprecated and did not find any more at this point.

**Comment by whlipscomb** [comment]
@gunterl, I made some progress on the review today.  Generally, the changes look great.   I still need to verify a couple of tests on Cheyenne, and next week I'd like to check that the tests run and plot on a Mac.  Then we can go ahead with the merge.

I made a new commit with some minor edits.  And I have a question about the ISMIP-HOM README file.  You added these two suggested links:
<http://homepages.vub.ac.be/~fpattyn/ismip/>
<http://homepages.vub.ac.be/~fpattyn/ismip/welcome.html/tc-2-95-2008-supplement.zip>

Neither of these works for me, so I wonder if we should take them out, or if they need to be updated again.
The original links were these:
<http://homepages.ulb.ac.be/~fpattyn/ismip/>
<http://homepages.ulb.ac.be/~fpattyn/ismip/tc-2-95-2008-supplement.zip>
For the first one, I get a permission error, but the second one (to get the big zip file) seems to work.

Also, I rebased my latest slab branch (lipscomb/update_slab3) onto your branch.  I then updated the scripts to python3, following your example.  They seem to work as intended.  I was wondering if you could check out this branch and diff the latest commit with the previous commit, to see if I've done a complete update.  Thanks!

**Comment by gunterl** [comment]
@whlipscomb you are right about the ISMIP-HOM readme file, the new links do not work anymore. Not sure what happened then.  At the time, I had problems with the older ones. Let's switch back to the older ones. 

Regarding the slab test: the stability test runs into a few CFL violation errors. I suggest reducing the time steps a bit to avoid this error. As for python compatibility, it looks good to me.

**Comment by ckhroulev** [comment]
@gunterl It looks like Frank Pattyn's page moved to https://frank.pattyn.web.ulb.be/ The current location of the ISMIP-HOM page appears to be https://frank.pattyn.web.ulb.be/ismip/welcome.html

**Pull request merged**
