### PR TITLE
New calving schemes for CalvingMIP and Antarctic simulations

### PR DESCRIPTION
**Pull request by whlipscomb**
This branch contains a new subgrid-scale calving front parameterization, along with several new calving schemes designed for the CalvingMIP project and realistic ice-sheet simulations.

Phase 1 of CalvingMIP (https://github.com/JRowanJordan/CalvingMIP/wiki) includes several experiments to test numerical implementation of calving-front (CF) schemes. Such schemes require a subgrid parameterization to maintain a sharp CF under advection. The CISM subgrid CF parameterization has been redesigned for CalvingMIP. The basic idea is as follows:

(1) Identify calving-front cells; these are grid cells with at least one ice-free ocean neighbor.
(2) For each CF cell with nonzero thickness H, compute an effective thickness H_eff, based on the maximum thickness of the neighboring interior cells. CF cells with H_eff < H are designated as partial CF cells; cells with H_eff = H are full cells.
(3) Before advection, identify the full and partial CF cells. After advection, any ice that has flowed from a partial CF cell to the open ocean is moved upstream to where it came from. This allows partial CF cells to fill without CF advance. Ice that has flowed out of full cells is allowed to remain, creating new partial CF cells.
(4) Based on the calving scheme we are using, compute a lateral calving rate Cr.
(5) Given Cr, compute the thickness loss associated with calving in each CF cell. This is given by dH = -Cr * dt * H_eff * CFl / (dx*dy), where CFl is the estimated length of the calving front within each CF cell, and dx and dy are the cell dimensions.

Several new calving options use this subgrid CF scheme:
* CF_ADVANCE_RETREAT_RATE = 6; forces the CF to retreat or advance at a prescribed rate, as in CalvingMIP
* CALVING_THCK_THRESHOLD = 7; computes the lateral calving rate based on a thickness threshold
* CALVING_STRESS = 8; computes the lateral calving rate based on the ratio between an effective stress and a prescribed stress threshold
* EIGEN_CALVING = 9; computes the lateral calving rate based on the eigenvalues of the strain rate tensor, following Levermann et al. (TC, 2012)
* CALVING_DAMAGE = 10; similar to option 8, but implemented using a damage scalar that is advected toward the calving front

Option 6 performs well for CalvingMIP Experiments 1–4. Experiments 1 and 2 are in a simple circular domain, while Experiments 3 and 4 are in the Thule domain with more complex basal topography. The amplitude and period of the advance/retreat cycle are specified in the config file. A Python script creates a netCDF input file and sets up the config files for each experiment.

For the other schemes, there has been some preliminary testing for Antarctic ice sheet spin-ups. Option 7 does not give realistic calving fronts, since observed CF thicknesses vary widely. Option 8 gives promising results, with a good match to observed CFs for most ice shelves. Option 9 works less well; it tends to allow spurious CF advance. Option 10 is technically supported but would need more testing and tuning to give realistic results.

### CODE REVIEW

**Comment by whlipscomb** [comment]
Adding some results of test problems:

- For the LIVVkit tests, this branch is BFB compared to the main branch for the dome, shelf, and stream tests. It fails each of the ISMIP-HOM tests (experiments A, C and F). However, the failure is at machine roundoff level, so the test performance isn't degraded. I don't think it's critical to figure out the source of a roundoff-level change.
- For a short Alps 200-m run, this branch is BFB as expected.
- For a short AIS 8-km run, the branch is not BFB. After a few years, there are small differences (~4th/5th/6th decimal place) in grounded ice area and integrated SMB, BMB, and calving fluxes, among other fields. This is expected, since there are some changes in the calving logic.

There do not appear to be any significant, unexplained changes.

**Comment by gunterl** [comment]
I ran a few test with this version, comparing it with the current version on main. Here are some observations:
1. mismip+ spinup
Need to modify the scripts mismip+Setup.py and mismip+.config.temp to make the test run. Once modified, the run is not BFB.
2. mismip3d spinup, ross
run BFB for thickness variables, not velocity variables.
3. ismip-hom, slab
runs are BFB

**Comment by whlipscomb** [comment]
@gunterl, thanks for running these tests. For the MISMIP+ spin-up, does "not BFB" mean roundoff-level differences (which I think we could expect), or more significant differences that need to be explained?

**Comment by gunterl** [comment]
@whlipscomb the not BFB means greater than roundoff-level differences. The difference are due to the change in configuration. These 2 lines differ from the config file on main:
which_ho_lateral_assemble = 1
which_ho_flotation_function = 3

Switching back these options to be 0 and 2 respectively yields non BFB behavior only near the calving front of the order of 1e-5 after 4000 years of spin-up procedure. These difference are very localized while other locations are BFB. the v-velocity is not BFB while the other variables are. Non of this (as far as I am concerned) is problematic.

**Comment by whlipscomb** [comment]
That sounds good. Thanks for checking.

**Review by gunterl — CHANGES_REQUESTED** [review]
Prior to merging to main, 2 files need to be modified in the mismip+ test to allow the test to run without error.
1. mismip+.config.template
add the line 
global_bc = 0
to the [grid] section of the config file.

2. mismip+Setup.py
a. Delete the line that remained due to a merge conflict (line 85).
b. add back the lines above xCalve (line 24):
xDomain = 640000
yDomain = 80000

**Comment by whlipscomb** [comment]
@gunterl, sorry for the delay. I made the changes you suggested in the mismip+ directory and pushed the changes to lipscomb/calvingmip on escomp. I think the branch is now ready to merge to main.

@Katetc, would you like to take care of the final merge?

**Comment by gunterl** [comment]
@whlipscomb I am sorry and I think I missed a few code changes that I did not capture last time. Here are additional changes that needs to happen:
1. In mismip+Setup.py
**line 81, add**: parser.add_argument('-g', '--gbc',   dest='global_bc',   type=int,    default=0,   help="global boundary condition")
** line line 83-86: remove them
**line 146: replace "options.xDomain" by "xDomain"
**line 147: replace "options.yDomain" by "yDomain"
**line 286: replace "options.yDomain" by "yDomain"

Without these changes, the setup does not run.

**Comment by whlipscomb** [comment]
@gunterl, I just redid the changes in mismip+Setup.py. I then did a forced commit that replaces the previous commit. Please check that his looks OK.

**Review by gunterl — APPROVED** [review]

**Review by Katetc — APPROVED** [review]

**Pull request merged**
