### PR TITLE
Change copyright year to 2018

### PR DESCRIPTION
**Pull request by billsacks**
I accomplished this for most files with:

git grep -l 'Copyright' |
 xargs sed -i.bk -e 's/Copyright (C) 2005-2017/Copyright (C) 2005-2018/'

Then manually fixed a few other files that weren't caught by that
(identified with 'git grep Copyright | grep -v 2018').

@whlipscomb @gunterl I'll wait to merge this until Bill L's final changes are in tomorrow. Then I'll merge up to the latest then merge this to master.

### CODE REVIEW

**Comment by whlipscomb** [comment]
@billsacks, I was running into the DS_Store issue myself.  I removed at least one such file from the repo, but I might have missed others. Not sure how they got there in the first place.

Anyway, thanks for taking care of this issue as well as the dates.

**Comment by billsacks** [comment]
The DS_Store files are created on a Mac when you do certain operations in the Finder (I think). It looks like @gunterl accidentally added them - maybe by doing something like a 'git add path/to/directory' of a directory that contained them?

**Comment by whlipscomb** [comment]
Good to know for future reference.  I think that happened when the various test directories were moved up a level.

**Comment by gunterl** [comment]
Oops, sorry about that. I'll be more cautious next time.

**Pull request merged**
